-- Seed the v1 exercise library (docs/TD.md — exercises). demo_keyframes
-- holds a movement "pattern" key the shared <ExerciseDemo> component maps to
-- one of its hand-authored SVG loops — adding an exercise never means new
-- animation code. adaptations is keyed by lowercase limitation tag;
-- `avoid: true` excludes the exercise from generation for that user,
-- otherwise the note surfaces as an amber adaptation block.

insert into exercises (slug, name, muscle_groups, equipment, difficulty, demo_keyframes, form_cues, common_mistakes, adaptations) values

-- Warm-ups / mobility
('arm-circles', 'Arm Circles', '{Delts,Mobility}', 'none', 1, '{"pattern":"press"}',
 'Small circles growing larger; keep shoulders down away from ears.',
 '{"Shrugging the shoulders up","Rushing — keep it smooth"}',
 '{"shoulder": {"note": "Stay in a pain-free range — smaller circles.", "avoid": false}}'),
('cat-cow', 'Cat-Cow', '{Core,Mobility}', 'none', 1, '{"pattern":"hold"}',
 'Move slowly between arching and rounding; sync with breath.',
 '{"Moving too fast","Holding your breath"}',
 '{"wrist": {"note": "Do it on fists or forearms.", "avoid": false}}'),
('light-march', 'March in Place', '{Cardio,Mobility}', 'none', 1, '{"pattern":"cardio"}',
 'Lift knees to hip height, swing arms naturally.',
 '{"Looking down","Shallow steps"}',
 '{}'),
('hip-circles', 'Hip Circles', '{Hip,Mobility}', 'none', 1, '{"pattern":"hold"}',
 'Hands on hips, slow controlled circles both directions.',
 '{"Moving from the knees instead of the hips"}',
 '{}'),
('childs-pose', 'Child''s Pose Stretch', '{Back,Mobility}', 'none', 1, '{"pattern":"hold"}',
 'Sit back onto heels, arms long, let the back lengthen.',
 '{"Forcing the stretch","Holding your breath"}',
 '{"knee": {"note": "Place a cushion behind the knees or skip.", "avoid": false}}'),

-- Bodyweight (none)
('squat-bodyweight', 'Bodyweight Squat', '{Quads,Glutes}', 'none', 1, '{"pattern":"squat"}',
 'Sit back like reaching for a chair behind you; drive knees out, chest tall.',
 '{"Knees caving inward","Heels lifting off the floor","Collapsing the chest"}',
 '{"knee": {"note": "Limit depth — stop above parallel, stay in a pain-free range.", "avoid": false}}'),
('glute-bridge', 'Glute Bridge', '{Glutes,Hamstrings}', 'none', 1, '{"pattern":"bridge"}',
 'Drive through the heels; squeeze glutes at the top, ribs down.',
 '{"Overarching the lower back","Pushing through the toes","Rushing the rep"}',
 '{"back": {"note": "Reduce range of motion; stop before the back arches.", "avoid": false}}'),
('push-up', 'Push-Up', '{Chest,Triceps}', 'none', 1, '{"pattern":"push"}',
 'Body in one line; elbows about 45° from the torso; full range.',
 '{"Sagging hips","Flaring elbows out wide","Half reps"}',
 '{"wrist": {"note": "Use fists or push-up handles to keep wrists neutral.", "avoid": false}, "shoulder": {"note": "Reduce depth; stop before any pinch.", "avoid": false}}'),
('incline-push-up', 'Incline Push-Up', '{Chest,Triceps}', 'none', 1, '{"pattern":"push"}',
 'Hands on a bench or counter; same straight-line body as a push-up.',
 '{"Hips sagging","Shrugging at the top"}',
 '{"wrist": {"note": "Use fists or handles to keep wrists neutral.", "avoid": false}}'),
('walking-lunge', 'Walking Lunge', '{Quads,Glutes}', 'none', 2, '{"pattern":"lunge"}',
 'Long step, both knees to 90°; front knee tracks over the foot.',
 '{"Front knee collapsing inward","Short choppy steps","Leaning forward"}',
 '{"knee": {"note": "Swap for glute bridges or shallow split squats.", "avoid": true}}'),
('plank', 'Plank', '{Core}', 'none', 1, '{"pattern":"hold"}',
 'Elbows under shoulders, squeeze glutes, one straight line.',
 '{"Hips too high","Lower back sagging","Holding your breath"}',
 '{"back": {"note": "Do it hands-elevated on a bench.", "avoid": false}, "wrist": {"note": "Stay on forearms.", "avoid": false}}'),
('dead-bug', 'Dead Bug', '{Core}', 'none', 1, '{"pattern":"hold"}',
 'Lower back pressed into the floor; move opposite arm and leg slowly.',
 '{"Back arching off the floor","Moving both sides at once"}',
 '{}'),
('bird-dog', 'Bird Dog', '{Core,Back}', 'none', 1, '{"pattern":"hold"}',
 'Reach long, not high; hips stay square to the floor.',
 '{"Rotating the hips","Lifting the arm/leg too high"}',
 '{"wrist": {"note": "Do it on fists.", "avoid": false}, "knee": {"note": "Pad under the knee.", "avoid": false}}'),
('superman-hold', 'Superman Hold', '{Back,Core}', 'none', 1, '{"pattern":"hold"}',
 'Lift chest and thighs a few cm; squeeze the whole back side.',
 '{"Craning the neck up","Jerking up instead of holding"}',
 '{"back": {"note": "Lift arms only, keep legs down.", "avoid": false}}'),
('calf-raise', 'Calf Raise', '{Calves}', 'none', 1, '{"pattern":"press"}',
 'Full stretch at the bottom, pause at the top.',
 '{"Bouncing","Partial range"}',
 '{"ankle": {"note": "Reduce range; hold support for balance.", "avoid": false}}'),
('jumping-jacks', 'Jumping Jacks', '{Cardio}', 'none', 1, '{"pattern":"cardio"}',
 'Land softly with knees slightly bent; steady rhythm.',
 '{"Landing stiff-legged","Shallow arm swing"}',
 '{"knee": {"note": "Step out side-to-side instead of jumping.", "avoid": true}, "ankle": {"note": "Step instead of jump.", "avoid": true}}'),
('mountain-climbers', 'Mountain Climbers', '{Cardio,Core}', 'none', 2, '{"pattern":"cardio"}',
 'Shoulders over wrists; drive knees in without bouncing hips.',
 '{"Hips piking up","Bouncing","Wrists drifting forward"}',
 '{"wrist": {"note": "Do them on fists or elevate hands.", "avoid": false}, "knee": {"note": "Slow the pace, smaller steps.", "avoid": false}}'),

-- Basic (bands/dumbbells)
('band-row', 'Band Row', '{Back,Biceps}', 'basic', 1, '{"pattern":"row"}',
 'Pull elbows past the ribs; squeeze shoulder blades together.',
 '{"Shrugging","Leaning back to cheat","Letting the band snap back"}',
 '{"elbow": {"note": "Lighter band, slower tempo.", "avoid": false}}'),
('db-row', 'Dumbbell Row', '{Back,Biceps}', 'basic', 1, '{"pattern":"row"}',
 'Flat back, pull the elbow to the hip, control the lowering.',
 '{"Rounding the back","Rotating the torso","Yanking the weight"}',
 '{"back": {"note": "Support your chest on an incline bench.", "avoid": false}, "elbow": {"note": "Lighter weight, fuller control.", "avoid": false}}'),
('db-shoulder-press', 'Dumbbell Shoulder Press', '{Delts,Triceps}', 'basic', 2, '{"pattern":"press"}',
 'Press straight up; ribs down, don''t lean back.',
 '{"Arching the lower back","Pressing forward instead of up"}',
 '{"shoulder": {"note": "Swap for front raises in a pain-free range.", "avoid": true}, "neck": {"note": "Keep the gaze forward, lighter weight.", "avoid": false}}'),
('db-rdl', 'Dumbbell Romanian Deadlift', '{Hamstrings,Glutes}', 'basic', 2, '{"pattern":"hinge"}',
 'Push hips back, soft knees; weights stay close to the legs.',
 '{"Rounding the back","Squatting instead of hinging","Overextending at the top"}',
 '{"back": {"note": "Reduce load and range; keep a neutral spine.", "avoid": false}}'),
('goblet-squat', 'Goblet Squat', '{Quads,Glutes}', 'basic', 2, '{"pattern":"squat"}',
 'Hold the weight at your chest; elbows track inside the knees.',
 '{"Knees caving inward","Dropping the chest","Heels lifting"}',
 '{"knee": {"note": "Limit depth, slow tempo.", "avoid": false}}'),
('db-bench-press', 'Dumbbell Bench Press', '{Chest,Triceps}', 'basic', 2, '{"pattern":"push"}',
 'Elbows about 45°; touch light at the bottom, press to full lockout.',
 '{"Flaring elbows","Bouncing at the bottom","Uneven pressing"}',
 '{"shoulder": {"note": "Limit depth — stop just above the chest.", "avoid": false}}'),
('band-pull-apart', 'Band Pull-Apart', '{Delts,Back}', 'basic', 1, '{"pattern":"row"}',
 'Arms straight, pull the band to your chest; squeeze the rear delts.',
 '{"Bending the elbows","Shrugging"}',
 '{}'),

-- Full gym
('barbell-back-squat', 'Barbell Back Squat', '{Quads,Glutes}', 'full_gym', 3, '{"pattern":"squat"}',
 'Brace hard, sit between the hips, drive the floor away.',
 '{"Knees caving inward","Chest collapsing","Rising hips-first"}',
 '{"back": {"note": "Swap for goblet squats or leg press.", "avoid": true}, "knee": {"note": "High-bar, controlled depth above parallel.", "avoid": false}}'),
('barbell-bench-press', 'Barbell Bench Press', '{Chest,Triceps}', 'full_gym', 2, '{"pattern":"push"}',
 'Shoulder blades pinned; bar to mid-chest; feet planted.',
 '{"Bouncing off the chest","Flaring elbows to 90°","Lifting hips off the bench"}',
 '{"shoulder": {"note": "Use dumbbells with a limited range instead.", "avoid": true}}'),
('lat-pulldown', 'Lat Pulldown', '{Back,Biceps}', 'full_gym', 1, '{"pattern":"row"}',
 'Pull the bar to the collarbone; chest up, elbows down and back.',
 '{"Leaning way back","Pulling behind the neck","Using momentum"}',
 '{"shoulder": {"note": "Neutral-grip handle, reduced range.", "avoid": false}}'),
('seated-cable-row', 'Seated Cable Row', '{Back,Biceps}', 'full_gym', 1, '{"pattern":"row"}',
 'Tall spine; pull to the belly button; squeeze, then control back.',
 '{"Rocking the torso","Shrugging","Rounding at the stretch"}',
 '{"back": {"note": "Reduce load; keep the torso upright throughout.", "avoid": false}}'),
('leg-press', 'Leg Press', '{Quads,Glutes}', 'full_gym', 1, '{"pattern":"squat"}',
 'Feet mid-platform; lower until thighs near 90°, don''t let hips curl.',
 '{"Bouncing at the bottom","Locking knees hard","Hips lifting off the pad"}',
 '{"knee": {"note": "Shallower range, lighter load.", "avoid": false}}'),
('treadmill-intervals', 'Treadmill Intervals', '{Cardio}', 'full_gym', 1, '{"pattern":"cardio"}',
 'Alternate brisk and easy paces; land mid-foot, stay tall.',
 '{"Holding the rails","Overstriding"}',
 '{"knee": {"note": "Use incline walking instead of running.", "avoid": false}, "ankle": {"note": "Flat, brisk walking only.", "avoid": false}}');
