-- Full-gym library expansion: real barbell lifts, machines, and cable work
-- for experienced lifters. Same contract as 0004: demo_keyframes holds a
-- pattern key the shared <ExerciseDemo> maps to a hand-authored SVG loop
-- (new patterns this pass: curl, latraise, pushdown, legext, legcurl, fly,
-- facepull). adaptations keyed by lowercase limitation tag; avoid:true
-- excludes the exercise from generation for that user.
--
-- Isolation arm work carries the extra 'Arms' tag so the
-- "Upper — Shoulders & Arms" day template finally has real matches.

insert into exercises (slug, name, muscle_groups, equipment, difficulty, demo_keyframes, form_cues, common_mistakes, adaptations) values

-- Barbell
('barbell-deadlift', 'Barbell Deadlift', '{Back,Glutes,Hamstrings,Compound}', 'full_gym', 3, '{"pattern":"hinge"}',
 'Bar over mid-foot; brace hard, push the floor away, finish tall — don''t yank.',
 '{"Rounding the lower back","Bar drifting away from the shins","Jerking the bar off the floor"}',
 '{"back": {"note": "", "avoid": true}, "hip": {"note": "Pull from blocks or rack pins to shorten the range.", "avoid": false}, "knee": {"note": "Keep shins vertical; trap-bar or block pulls if it pinches.", "avoid": false}}'),
('barbell-romanian-deadlift', 'Romanian Deadlift', '{Hamstrings,Glutes,Back}', 'full_gym', 2, '{"pattern":"hinge"}',
 'Soft knees, push the hips back until the hamstrings load; bar stays on the thighs.',
 '{"Turning it into a squat","Rounding as the bar passes the knees","Overreaching the bottom"}',
 '{"back": {"note": "", "avoid": true}, "hip": {"note": "Shorten the range — stop mid-shin.", "avoid": false}}'),
('barbell-overhead-press', 'Overhead Press', '{Delts,Triceps,Compound}', 'full_gym', 2, '{"pattern":"press"}',
 'Squeeze glutes, ribs down; press slightly back so the bar finishes over mid-foot.',
 '{"Leaning back to grind the rep","Flaring the elbows out","Pressing around the chin instead of moving it"}',
 '{"shoulder": {"note": "", "avoid": true}, "back": {"note": "Brace hard or press seated with back support.", "avoid": false}, "neck": {"note": "Keep the gaze forward, don''t chase the bar with your chin.", "avoid": false}}'),
('barbell-bent-over-row', 'Barbell Row', '{Back,Biceps,Compound}', 'full_gym', 2, '{"pattern":"row"}',
 'Hinge to ~45°, brace, pull the bar to the lower ribs; torso stays still.',
 '{"Standing up with every rep","Yanking with the arms first","Rounding the lower back"}',
 '{"back": {"note": "", "avoid": true}, "elbow": {"note": "Use straps so the grip isn''t the limiter.", "avoid": false}}'),
('barbell-incline-press', 'Incline Bench Press', '{Chest,Delts,Triceps}', 'full_gym', 2, '{"pattern":"push"}',
 'Bench at 30–45°; touch the upper chest, elbows ~45° from the torso.',
 '{"Bouncing the bar off the chest","Flaring elbows to 90°","Losing upper-back tightness"}',
 '{"shoulder": {"note": "Lower the incline and stop an inch off the chest.", "avoid": false}, "wrist": {"note": "Stack knuckles over forearms; slightly narrower grip.", "avoid": false}}'),
('barbell-hip-thrust', 'Barbell Hip Thrust', '{Glutes,Hamstrings}', 'full_gym', 2, '{"pattern":"bridge"}',
 'Upper back on the bench, chin tucked; drive through the heels to a full lockout.',
 '{"Overarching at the top","Pushing through the toes","Half-range reps"}',
 '{"back": {"note": "Squeeze glutes, ribs down — don''t finish with the spine.", "avoid": false}, "hip": {"note": "Pad the bar well and stay in a pain-free range.", "avoid": false}}'),
('barbell-front-squat', 'Front Squat', '{Quads,Core,Compound}', 'full_gym', 3, '{"pattern":"squat"}',
 'Elbows high, bar on the shoulders; sit straight down between the heels.',
 '{"Elbows dropping and dumping the bar","Heels lifting","Knees caving inward"}',
 '{"knee": {"note": "Limit depth to a pain-free range.", "avoid": false}, "wrist": {"note": "Use a cross-arm grip or straps instead of a full rack grip.", "avoid": false}}'),
('ez-bar-curl', 'EZ-Bar Curl', '{Biceps,Arms}', 'full_gym', 1, '{"pattern":"curl"}',
 'Elbows pinned to your sides; curl up without swinging, lower under control.',
 '{"Swinging the hips to cheat","Elbows drifting forward","Dropping the bar down"}',
 '{"elbow": {"note": "Lighter weight, stop short of full extension.", "avoid": false}, "wrist": {"note": "The angled grip helps — keep wrists neutral, don''t let them bend back.", "avoid": false}}'),

-- Machines
('leg-extension', 'Leg Extension', '{Quads}', 'full_gym', 1, '{"pattern":"legext"}',
 'Pad on the shins, knees lined up with the pivot; pause a beat at the top.',
 '{"Kicking the weight up with momentum","Letting the stack slam down","Hips lifting off the seat"}',
 '{"knee": {"note": "Light weight, pain-free range only — skip the last few degrees.", "avoid": false}}'),
('seated-leg-curl', 'Seated Leg Curl', '{Hamstrings}', 'full_gym', 1, '{"pattern":"legcurl"}',
 'Knees at the pivot, curl the pad under you; control the return fully.',
 '{"Hips rising off the seat","Half-range reps","Letting the stack yank the legs back"}',
 '{"knee": {"note": "Lighter load, smooth tempo, pain-free range.", "avoid": false}}'),
('hack-squat', 'Hack Squat', '{Quads,Glutes}', 'full_gym', 2, '{"pattern":"squat"}',
 'Back flat on the pad, feet mid-platform; lower under control to ~90°.',
 '{"Bouncing out of the bottom","Knees caving inward","Heels lifting off the platform"}',
 '{"knee": {"note": "Shallower range, feet higher on the platform.", "avoid": false}, "back": {"note": "Keep the hips glued to the pad — don''t let them curl under.", "avoid": false}}'),
('chest-press-machine', 'Chest Press Machine', '{Chest,Triceps}', 'full_gym', 1, '{"pattern":"push"}',
 'Handles at mid-chest height; press smooth, stop just short of locked elbows.',
 '{"Shoulders shrugging toward the ears","Slamming the stack between reps","Half-pressing with a fast tempo"}',
 '{"shoulder": {"note": "Shorten the range — don''t let the handles come all the way back.", "avoid": false}}'),
('pec-deck', 'Pec Deck Fly', '{Chest}', 'full_gym', 1, '{"pattern":"fly"}',
 'Elbows slightly bent and fixed; squeeze the pads together, open only to a mild stretch.',
 '{"Opening too far behind the torso","Pressing instead of squeezing","Rushing the negative"}',
 '{"shoulder": {"note": "Limit how far the arms open — stay in front of the shoulder line.", "avoid": false}}'),
('shoulder-press-machine', 'Shoulder Press Machine', '{Delts,Triceps}', 'full_gym', 1, '{"pattern":"press"}',
 'Seat height so handles start at ear level; press up without shrugging.',
 '{"Arching off the back pad","Shrugging into the ears","Locking out hard every rep"}',
 '{"shoulder": {"note": "Swap for front raises in a pain-free range.", "avoid": true}, "neck": {"note": "Keep the gaze forward, lighter weight.", "avoid": false}}'),
('assisted-pullup', 'Assisted Pull-Up', '{Back,Biceps}', 'full_gym', 1, '{"pattern":"pullup"}',
 'Set assistance so you get clean full reps; chest to the bar, control the way down.',
 '{"Kipping off the knee pad","Chin-poking at the top","Dropping through the negative"}',
 '{"shoulder": {"note": "Neutral-grip handles if available, stop below full hang.", "avoid": false}, "elbow": {"note": "More assistance, smooth tempo.", "avoid": false}}'),
('calf-raise-machine', 'Calf Raise Machine', '{Calves}', 'full_gym', 1, '{"pattern":"calfraise"}',
 'Full stretch at the bottom, pause at the top; no bouncing.',
 '{"Bouncing out of the stretch","Bending the knees to move more weight","Partial reps at the top only"}',
 '{"ankle": {"note": "Reduced range from the floor instead of a step; lighter load.", "avoid": false}}'),
('back-extension', 'Back Extension', '{Back,Glutes,Hamstrings}', 'full_gym', 1, '{"pattern":"hinge"}',
 'Hinge at the hips, not the waist; squeeze glutes to come up level — no higher.',
 '{"Hyperextending past level","Rounding on the way down","Swinging with momentum"}',
 '{"back": {"note": "Bodyweight only, short range, stop the set well before fatigue.", "avoid": false}}'),

-- Cables
('cable-tricep-pushdown', 'Triceps Pushdown', '{Triceps,Arms}', 'full_gym', 1, '{"pattern":"pushdown"}',
 'Elbows pinned to your sides; press to full extension, control the return.',
 '{"Leaning body weight onto the bar","Elbows flaring out","Letting the cable pull the arms up fast"}',
 '{"elbow": {"note": "Rope attachment, lighter weight, stop short of hard lockout.", "avoid": false}, "wrist": {"note": "Use the rope and keep wrists neutral.", "avoid": false}}'),
('cable-curl', 'Cable Curl', '{Biceps,Arms}', 'full_gym', 1, '{"pattern":"curl"}',
 'Step back so the cable is taut at the bottom; curl without leaning back.',
 '{"Swinging the torso","Elbows drifting forward","Losing tension at the bottom"}',
 '{"elbow": {"note": "Lighter weight, stop short of full extension.", "avoid": false}}'),
('cable-fly', 'Cable Fly', '{Chest}', 'full_gym', 1, '{"pattern":"fly"}',
 'Slight forward lean, elbows softly bent; hug the handles together in a wide arc.',
 '{"Turning it into a press","Opening too deep behind the shoulders","Shrugging as the hands meet"}',
 '{"shoulder": {"note": "Shorten the arc — hands stay in front of the shoulder line.", "avoid": false}}'),
('face-pull', 'Face Pull', '{Delts,Back}', 'full_gym', 1, '{"pattern":"facepull"}',
 'Rope at eye height; pull toward the bridge of your nose, elbows high and wide.',
 '{"Using too much weight","Pulling to the chest instead of the face","Shoulders rolling forward"}',
 '{"shoulder": {"note": "Light weight and slow tempo — usually shoulder-friendly.", "avoid": false}, "neck": {"note": "Don''t crane the head forward to meet the rope.", "avoid": false}}'),
('cable-crunch', 'Cable Crunch', '{Core}', 'full_gym', 1, '{"pattern":"situp"}',
 'Kneel tall, rope beside the ears; crunch the ribs toward the hips, hips stay still.',
 '{"Pulling with the arms","Hinging at the hips instead of flexing the spine","Standing up between reps"}',
 '{"back": {"note": "Smaller range, lighter stack.", "avoid": false}, "neck": {"note": "Keep the rope anchored beside the head — don''t tug it down.", "avoid": false}}'),

-- Dumbbells (bench work needs the gym; the last two only need dumbbells)
('incline-db-press', 'Incline Dumbbell Press', '{Chest,Delts}', 'full_gym', 2, '{"pattern":"push"}',
 'Bench at 30°; press the dumbbells up and slightly together, full stretch at the bottom.',
 '{"Flaring elbows to 90°","Clanking the dumbbells at the top","Arching off the bench"}',
 '{"shoulder": {"note": "Lower the incline and shorten the bottom range.", "avoid": false}}'),
('db-lateral-raise', 'Dumbbell Lateral Raise', '{Delts,Arms}', 'basic', 1, '{"pattern":"latraise"}',
 'Lead with the elbows, soft bend; raise to shoulder height, pour-the-jug wrists.',
 '{"Swinging the weights up","Raising above shoulder height","Shrugging the traps"}',
 '{"shoulder": {"note": "Stop below shoulder height, thumbs slightly up.", "avoid": false}}'),
('db-hammer-curl', 'Hammer Curl', '{Biceps,Arms}', 'basic', 1, '{"pattern":"curl"}',
 'Palms facing each other; curl without swinging, control the lowering.',
 '{"Swinging the hips","Elbows drifting forward","Rushing the negative"}',
 '{"elbow": {"note": "Lighter weight, stop short of full extension.", "avoid": false}, "wrist": {"note": "The neutral grip is wrist-friendly — keep it locked, don''t let it flex.", "avoid": false}}');
